// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBpj_mMzOb8NHhCJc--jjGv8R0LfqM8Tg',
    appId: '1:60831915765:web:2685da650bc116447a2fbc',
    messagingSenderId: '60831915765',
    projectId: 'anabool-iyref',
    authDomain: 'anabool-iyref.firebaseapp.com',
    storageBucket: 'anabool-iyref.firebasestorage.app',
    measurementId: 'G-CWWCP0S3PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDn2oQESfmajkIsgDEf4xrsf02u58FPQ',
    appId: '1:60831915765:android:6ba14bf9d83d9c9b7a2fbc',
    messagingSenderId: '60831915765',
    projectId: 'anabool-iyref',
    storageBucket: 'anabool-iyref.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGsusQQ0rd7H3MWlx5Uwzsc-qn8Dgkos',
    appId: '1:60831915765:ios:1c60783ebfcedf457a2fbc',
    messagingSenderId: '60831915765',
    projectId: 'anabool-iyref',
    storageBucket: 'anabool-iyref.firebasestorage.app',
    iosBundleId: 'com.anabool.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGsusQQ0rd7H3MWlx5Uwzsc-qn8Dgkos',
    appId: '1:60831915765:ios:1c60783ebfcedf457a2fbc',
    messagingSenderId: '60831915765',
    projectId: 'anabool-iyref',
    storageBucket: 'anabool-iyref.firebasestorage.app',
    iosBundleId: 'com.anabool.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBpj_mMzOb8NHhCJc--jjGv8R0LfqM8Tg',
    appId: '1:60831915765:web:a88fb41da7efb7ad7a2fbc',
    messagingSenderId: '60831915765',
    projectId: 'anabool-iyref',
    authDomain: 'anabool-iyref.firebaseapp.com',
    storageBucket: 'anabool-iyref.firebasestorage.app',
    measurementId: 'G-MCV68422DT',
  );
}
